title: "Marijan's personal portfolio" # the name of your site, e.g. ACME Corp.
tagline: "showcae of projects I'w done"
email: hello@marijan.xyz
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
author: Marijan Brvar
url: "http://www.marijan.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: ""
twitter:
  username: marijanbrvar
  card: summary #keep this to generate a twitter share card

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  works:
    output: true
